### PR TITLE
Some fixes and improvements on Html5Field

### PR DESCRIPTION
**Pull request by niwinz**
I added a subclass of Form with methods that make error output more suitable for jquery validator.
I have corrected a few things, and I added a new field.
I have also written several tests, and have included setup.py of another fork.

### CODE REVIEW

**Comment by adamcupial** [comment]
It's html5 forms, only client-side validation I was going to use was one from html5, not jQuery, thats the only change I'm not particulary happy about.

**Comment by niwinz** [comment]
He believed it would be interesting to include it because I use it in production of various projects.
I was thinking about adding other small improvements to Form, but I think it would be best to separate it from django-html5-forms and have it as a dependency. What do you think about this?

**Comment by adamcupial** [comment]
Yes, probably It would be best. 
I try to follow unix philosophy: One thing, do it well
django-html5 is supposed to be a set of Html5Fields for django, to replace standard django.forms for those that want to try html5 ones, it shouldn't have jquery-specific changes in it

**Comment by niwinz** [comment]
Sounds good. Then, remove the Form class, and I create a separate project to publish the further enhancements to Form.
I think so will be better.

**Pull request merged**
